// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: user.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	StreamGreeter_GoodAdd_FullMethodName    = "/proto.StreamGreeter/GoodAdd"
	StreamGreeter_GoodUpdate_FullMethodName = "/proto.StreamGreeter/GoodUpdate"
	StreamGreeter_GoodList_FullMethodName   = "/proto.StreamGreeter/GoodList"
	StreamGreeter_GoodDelete_FullMethodName = "/proto.StreamGreeter/GoodDelete"
)

// StreamGreeterClient is the client API for StreamGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamGreeterClient interface {
	GoodAdd(ctx context.Context, in *GoodAddReq, opts ...grpc.CallOption) (*GoodAddResp, error)
	GoodUpdate(ctx context.Context, in *GoodUpdateReq, opts ...grpc.CallOption) (*GoodUpdateResp, error)
	GoodList(ctx context.Context, in *GoodListReq, opts ...grpc.CallOption) (*GoodListResp, error)
	GoodDelete(ctx context.Context, in *GoodDeleteReq, opts ...grpc.CallOption) (*GoodDeleteResp, error)
}

type streamGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamGreeterClient(cc grpc.ClientConnInterface) StreamGreeterClient {
	return &streamGreeterClient{cc}
}

func (c *streamGreeterClient) GoodAdd(ctx context.Context, in *GoodAddReq, opts ...grpc.CallOption) (*GoodAddResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodAddResp)
	err := c.cc.Invoke(ctx, StreamGreeter_GoodAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamGreeterClient) GoodUpdate(ctx context.Context, in *GoodUpdateReq, opts ...grpc.CallOption) (*GoodUpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodUpdateResp)
	err := c.cc.Invoke(ctx, StreamGreeter_GoodUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamGreeterClient) GoodList(ctx context.Context, in *GoodListReq, opts ...grpc.CallOption) (*GoodListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodListResp)
	err := c.cc.Invoke(ctx, StreamGreeter_GoodList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamGreeterClient) GoodDelete(ctx context.Context, in *GoodDeleteReq, opts ...grpc.CallOption) (*GoodDeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodDeleteResp)
	err := c.cc.Invoke(ctx, StreamGreeter_GoodDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamGreeterServer is the server API for StreamGreeter service.
// All implementations must embed UnimplementedStreamGreeterServer
// for forward compatibility
type StreamGreeterServer interface {
	GoodAdd(context.Context, *GoodAddReq) (*GoodAddResp, error)
	GoodUpdate(context.Context, *GoodUpdateReq) (*GoodUpdateResp, error)
	GoodList(context.Context, *GoodListReq) (*GoodListResp, error)
	GoodDelete(context.Context, *GoodDeleteReq) (*GoodDeleteResp, error)
	mustEmbedUnimplementedStreamGreeterServer()
}

// UnimplementedStreamGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedStreamGreeterServer struct {
}

func (UnimplementedStreamGreeterServer) GoodAdd(context.Context, *GoodAddReq) (*GoodAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodAdd not implemented")
}
func (UnimplementedStreamGreeterServer) GoodUpdate(context.Context, *GoodUpdateReq) (*GoodUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodUpdate not implemented")
}
func (UnimplementedStreamGreeterServer) GoodList(context.Context, *GoodListReq) (*GoodListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodList not implemented")
}
func (UnimplementedStreamGreeterServer) GoodDelete(context.Context, *GoodDeleteReq) (*GoodDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodDelete not implemented")
}
func (UnimplementedStreamGreeterServer) mustEmbedUnimplementedStreamGreeterServer() {}

// UnsafeStreamGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamGreeterServer will
// result in compilation errors.
type UnsafeStreamGreeterServer interface {
	mustEmbedUnimplementedStreamGreeterServer()
}

func RegisterStreamGreeterServer(s grpc.ServiceRegistrar, srv StreamGreeterServer) {
	s.RegisterService(&StreamGreeter_ServiceDesc, srv)
}

func _StreamGreeter_GoodAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).GoodAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_GoodAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).GoodAdd(ctx, req.(*GoodAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamGreeter_GoodUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).GoodUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_GoodUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).GoodUpdate(ctx, req.(*GoodUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamGreeter_GoodList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).GoodList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_GoodList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).GoodList(ctx, req.(*GoodListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamGreeter_GoodDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).GoodDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_GoodDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).GoodDelete(ctx, req.(*GoodDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamGreeter_ServiceDesc is the grpc.ServiceDesc for StreamGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StreamGreeter",
	HandlerType: (*StreamGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GoodAdd",
			Handler:    _StreamGreeter_GoodAdd_Handler,
		},
		{
			MethodName: "GoodUpdate",
			Handler:    _StreamGreeter_GoodUpdate_Handler,
		},
		{
			MethodName: "GoodList",
			Handler:    _StreamGreeter_GoodList_Handler,
		},
		{
			MethodName: "GoodDelete",
			Handler:    _StreamGreeter_GoodDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
